In [1]:
import pandas as pd

In [2]:
train_samples = pd.read_csv("train_dataset_advanced.csv")
val_samples = pd.read_csv('val_dataset_advanced.csv')

In [3]:
train_samples.head(3)

,user_id,post_id,target,topic,text_len,word_count,text,gender,age,country,...,like_topic_covid,like_topic_entertainment,like_topic_movie,like_topic_politics,like_topic_sport,like_topic_tech,most_common_topic,topic_match,len_diff_from_avg_view,len_ratio_from_avg_view
0,200,1452,1,sport,3393,563,Middlesbrough 2-2 Charlton\n\nA late header by...,1,34,Russia,...,2.0,1.0,6.0,2.0,4.0,0.0,movie,0,1816.757764,2.151223
1,200,6919,1,movie,799,137,Methinks the best screen version of Quo Vadis?...,1,34,Russia,...,2.0,1.0,6.0,2.0,4.0,0.0,movie,1,-777.242236,0.506580
2,200,7143,1,movie,660,111,Heartland was in production about the same tim...,1,34,Russia,...,2.0,1.0,6.0,2.0,4.0,0.0,movie,1,-916.242236,0.418452

In [4]:
train_samples.shape, val_samples.shape

((6048228, 40), (3136970, 40))

In [5]:
from catboost import Pool, CatBoostClassifier

# Определим списки признаков
cat_features_names = ['gender', 'country', 'city', 'os', 'source', 'topic', 'most_common_topic']

# Все остальные числовые (кроме user_id, post_id, target)
feature_names = [col for col in train_samples.columns if col not in ['user_id', 'post_id', 'target', 'text']]

# Создаём Pool
train_pool = Pool(
    data=train_samples[feature_names],
    label=train_samples['target'],
    cat_features=cat_features_names,
)

val_pool = Pool(
    data=val_samples[feature_names],
    label=val_samples['target'],
    cat_features=cat_features_names,
)

print("Готово к обучению CatBoost!")

Готово к обучению CatBoost!

In [6]:
model = CatBoostClassifier(
    iterations=500,
    early_stopping_rounds=200,
    eval_metric="AUC",
    max_depth=None,
    learning_rate=0.1,
)

In [7]:
model.fit(train_pool, eval_set=val_pool, verbose=25)

0:	test: 0.5721789	best: 0.5721789 (0)	total: 1.19s	remaining: 9m 53s
25:	test: 0.6101201	best: 0.6104208 (17)	total: 21.7s	remaining: 6m 36s
50:	test: 0.6225797	best: 0.6225797 (50)	total: 47.3s	remaining: 6m 56s
75:	test: 0.6241906	best: 0.6245418 (69)	total: 1m 13s	remaining: 6m 47s
100:	test: 0.6242466	best: 0.6245418 (69)	total: 1m 37s	remaining: 6m 25s
125:	test: 0.6233107	best: 0.6245418 (69)	total: 2m 2s	remaining: 6m 3s
150:	test: 0.6234039	best: 0.6245418 (69)	total: 2m 27s	remaining: 5m 41s
175:	test: 0.6228131	best: 0.6245418 (69)	total: 2m 52s	remaining: 5m 18s
200:	test: 0.6225214	best: 0.6245418 (69)	total: 3m 16s	remaining: 4m 52s
225:	test: 0.6215210	best: 0.6245418 (69)	total: 3m 42s	remaining: 4m 29s
250:	test: 0.6206681	best: 0.6245418 (69)	total: 4m 8s	remaining: 4m 6s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.6245418439
bestIteration = 69

Shrink model to first 70 iterations.

In [8]:
pd.DataFrame({
    "name": model.feature_names_,
    "fi": model.get_feature_importance(), 
}).sort_values("fi", ascending=False)

                        name         fi
6                       city  21.576667
7                  exp_group  19.407060
0                      topic  14.162754
4                        age  13.958539
15              unique_likes   7.064214
14               total_likes   4.746534
2                 word_count   3.836420
11              unique_views   2.869816
3                     gender   2.820522
32         most_common_topic   2.594798
30          like_topic_sport   1.549633
10               total_views   1.263163
5                    country   1.236113
21          view_topic_movie   0.805681
31           like_topic_tech   0.729385
19          view_topic_covid   0.481007
1                   text_len   0.286810
35   len_ratio_from_avg_view   0.135086
26          like_topic_covid   0.111590
34    len_diff_from_avg_view   0.110996
29       like_topic_politics   0.101118
33               topic_match   0.096945
12       avg_text_len_viewed   0.055151
17      avg_word_count_liked   0.000000
28          like_topic_movie   0.000000
8                         os   0.000000
9                     source   0.000000
27  like_topic_entertainment   0.000000
16        avg_text_len_liked   0.000000
25       like_topic_business   0.000000
24           view_topic_tech   0.000000
23          view_topic_sport   0.000000
22       view_topic_politics   0.000000
13     avg_word_count_viewed   0.000000
20  view_topic_entertainment   0.000000
18       view_topic_business   0.000000

In [11]:
import optuna
from catboost import CatBoostClassifier, Pool
import numpy as np

def objective(trial, train_pool, val_pool):
    # Задаём пространство поиска
    params = {
        'iterations': 2000,
        'early_stopping_rounds': 200,
        'eval_metric': 'AUC',
        'loss_function': trial.suggest_categorical("loss_function", ["Logloss", "CrossEntropy"]),
        'task_type': 'CPU',
        'thread_count': -1,
        'random_seed': 42,
        'verbose': False,
        'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.5),
        'depth': trial.suggest_int('depth', 4, 10),
        'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1, 10),
        'bagging_temperature': trial.suggest_uniform('bagging_temperature', 0, 1),
        'border_count': trial.suggest_int('border_count', 32, 255),
        'random_strength': trial.suggest_uniform('random_strength', 0, 2),
        'one_hot_max_size':  trial.suggest_int('one_hot_max_size', 2, 10),
    }
    
    # Обучаем модель
    model = CatBoostClassifier(**params)
    model.fit(train_pool, eval_set=val_pool, verbose_eval=False)
    
    # Извлекаем лучшее значение метрики на валидации
    best_auc = model.best_score_['validation']['AUC']
    
    return best_auc

In [12]:
from optuna.pruners import MedianPruner
from optuna.samplers import TPESampler

# Создаём study с направлением максимизации AUC
study = optuna.create_study(
    direction='maximize',
    sampler=TPESampler(seed=42),
    pruner=MedianPruner(n_startup_trials=5, n_warmup_steps=10)
)

objective_func = lambda trial: objective(trial, train_pool, val_pool)

# Оптимизация (например, 30 попыток)
study.optimize(objective_func, n_trials=30, show_progress_bar=True)

[I 2026-03-03 16:44:32,673] A new study created in memory with name: no-name-d6924ecd-693f-4d6a-ba86-81426ba24e6d
  0%|          | 0/30 [00:00<?, ?it/s]/var/folders/9q/zwzshfys2s32y6mnrh7crj1m0000gp/T/ipykernel_3888/385456407.py:16: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'learning_rate': trial.suggest_loguniform('learning_rate', 1e-3, 0.5),
/var/folders/9q/zwzshfys2s32y6mnrh7crj1m0000gp/T/ipykernel_3888/385456407.py:18: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  'l2_leaf_reg': trial.suggest_loguniform('l2_leaf_reg', 1, 10),
/var/folders/9q/zwzshfys2s32y6mnrh7crj1m0000gp/T/ipykernel_3888/385456407.py:19: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'bagging_temperature': trial.suggest_uniform('bagging_temperature', 0, 1),
/var/folders/9q/zwzshfys2s32y6mnrh7crj1m0000gp/T/ipykernel_3888/385456407.py:21: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float instead.
  'random_strength': trial.suggest_uniform('random_strength', 0, 2),
Best trial: 0. Best value: 0.625628:   3%|▎         | 1/30 [04:05<1:58:46, 245.73s/it]

[I 2026-03-03 16:48:38,382] Trial 0 finished with value: 0.6256281908658784 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.09454306819536165, 'depth': 8, 'l2_leaf_reg': 1.4322493718230251, 'bagging_temperature': 0.15599452033620265, 'border_count': 45, 'random_strength': 1.7323522915498704, 'one_hot_max_size': 7}. Best is trial 0 with value: 0.6256281908658784.

Best trial: 0. Best value: 0.625628:   7%|▋         | 2/30 [08:22<1:57:35, 251.97s/it]

[I 2026-03-03 16:52:54,731] Trial 1 finished with value: 0.6246765460607083 and parameters: {'loss_function': 'Logloss', 'learning_rate': 0.4147225000481636, 'depth': 9, 'l2_leaf_reg': 1.6305687346221471, 'bagging_temperature': 0.18182496720710062, 'border_count': 73, 'random_strength': 0.6084844859190754, 'one_hot_max_size': 6}. Best is trial 0 with value: 0.6256281908658784.

Best trial: 0. Best value: 0.625628:  10%|█         | 3/30 [16:30<2:41:56, 359.85s/it]

[I 2026-03-03 17:01:02,965] Trial 2 finished with value: 0.625151130211378 and parameters: {'loss_function': 'Logloss', 'learning_rate': 0.044809759182149515, 'depth': 4, 'l2_leaf_reg': 1.9594972058679163, 'bagging_temperature': 0.3663618432936917, 'border_count': 134, 'random_strength': 1.5703519227860272, 'one_hot_max_size': 3}. Best is trial 0 with value: 0.6256281908658784.

Best trial: 0. Best value: 0.625628:  13%|█▎        | 4/30 [43:11<6:08:15, 849.83s/it]

[I 2026-03-03 17:27:43,911] Trial 3 finished with value: 0.6204651321156658 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.0013346527038305934, 'depth': 8, 'l2_leaf_reg': 1.4808945119975185, 'bagging_temperature': 0.06505159298527952, 'border_count': 244, 'random_strength': 1.9312640661491187, 'one_hot_max_size': 9}. Best is trial 0 with value: 0.6256281908658784.

Best trial: 0. Best value: 0.625628:  17%|█▋        | 5/30 [49:08<4:40:07, 672.31s/it]

[I 2026-03-03 17:33:41,484] Trial 4 finished with value: 0.6249177606124559 and parameters: {'loss_function': 'Logloss', 'learning_rate': 0.07026263205443048, 'depth': 7, 'l2_leaf_reg': 1.324458134009935, 'bagging_temperature': 0.4951769101112702, 'border_count': 39, 'random_strength': 1.8186408041575641, 'one_hot_max_size': 4}. Best is trial 0 with value: 0.6256281908658784.

Best trial: 5. Best value: 0.625639:  20%|██        | 6/30 [56:16<3:55:42, 589.25s/it]

[I 2026-03-03 17:40:49,464] Trial 5 finished with value: 0.6256387266684198 and parameters: {'loss_function': 'Logloss', 'learning_rate': 0.02533074654001447, 'depth': 7, 'l2_leaf_reg': 1.5305744365500176, 'bagging_temperature': 0.9695846277645586, 'border_count': 205, 'random_strength': 1.8789978831283782, 'one_hot_max_size': 10}. Best is trial 5 with value: 0.6256387266684198.

Best trial: 5. Best value: 0.625639:  23%|██▎       | 7/30 [1:13:32<4:41:51, 735.30s/it]

[I 2026-03-03 17:58:05,476] Trial 6 finished with value: 0.6164133908384244 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.0017331598058558703, 'depth': 5, 'l2_leaf_reg': 1.1097554561103098, 'bagging_temperature': 0.32533033076326434, 'border_count': 119, 'random_strength': 0.5426980635477918, 'one_hot_max_size': 9}. Best is trial 5 with value: 0.6256387266684198.

Best trial: 5. Best value: 0.625639:  27%|██▋       | 8/30 [1:24:24<4:19:53, 708.81s/it]

[I 2026-03-03 18:08:57,563] Trial 7 finished with value: 0.6251776839201293 and parameters: {'loss_function': 'Logloss', 'learning_rate': 0.029155497059176992, 'depth': 4, 'l2_leaf_reg': 6.341572775495278, 'bagging_temperature': 0.07455064367977082, 'border_count': 253, 'random_strength': 1.5444895385933148, 'one_hot_max_size': 3}. Best is trial 5 with value: 0.6256387266684198.

Best trial: 8. Best value: 0.626289:  30%|███       | 9/30 [1:29:12<3:22:00, 577.18s/it]

[I 2026-03-03 18:13:45,300] Trial 8 finished with value: 0.6262891255682919 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.0808698743602125, 'depth': 9, 'l2_leaf_reg': 5.905685925060636, 'bagging_temperature': 0.07404465173409036, 'border_count': 112, 'random_strength': 0.23173811905025943, 'one_hot_max_size': 9}. Best is trial 8 with value: 0.6262891255682919.

Best trial: 8. Best value: 0.626289:  33%|███▎      | 10/30 [1:52:40<4:37:51, 833.57s/it]

[I 2026-03-03 18:37:12,994] Trial 9 finished with value: 0.6169915690275658 and parameters: {'loss_function': 'Logloss', 'learning_rate': 0.0014843697010415793, 'depth': 6, 'l2_leaf_reg': 2.114381362663436, 'bagging_temperature': 0.7296061783380641, 'border_count': 174, 'random_strength': 1.774425485152653, 'one_hot_max_size': 6}. Best is trial 8 with value: 0.6262891255682919.

Best trial: 10. Best value: 0.626568:  37%|███▋      | 11/30 [2:14:50<5:12:05, 985.55s/it]

[I 2026-03-03 18:59:23,144] Trial 10 finished with value: 0.6265680541198797 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.0065046290361779335, 'depth': 10, 'l2_leaf_reg': 8.788024316573402, 'bagging_temperature': 0.715169612196795, 'border_count': 99, 'random_strength': 0.030876792635755573, 'one_hot_max_size': 8}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  40%|████      | 12/30 [2:36:34<5:24:44, 1082.47s/it]

[I 2026-03-03 19:21:07,285] Trial 11 finished with value: 0.6262981030774417 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.006443517625684419, 'depth': 10, 'l2_leaf_reg': 9.208672937212778, 'bagging_temperature': 0.6776742687906088, 'border_count': 97, 'random_strength': 0.0340916839877708, 'one_hot_max_size': 8}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  43%|████▎     | 13/30 [2:57:03<5:19:16, 1126.86s/it]

[I 2026-03-03 19:41:36,296] Trial 12 finished with value: 0.6265221696748401 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.006024380321322259, 'depth': 10, 'l2_leaf_reg': 9.331921159395208, 'bagging_temperature': 0.6987981666202414, 'border_count': 87, 'random_strength': 0.069081368936935, 'one_hot_max_size': 7}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  47%|████▋     | 14/30 [3:25:37<5:47:44, 1304.02s/it]

[I 2026-03-03 20:10:09,666] Trial 13 finished with value: 0.6250267921531636 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.005680788286158302, 'depth': 10, 'l2_leaf_reg': 9.908696623768996, 'bagging_temperature': 0.8197771830370537, 'border_count': 77, 'random_strength': 1.0731214139790004, 'one_hot_max_size': 5}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  50%|█████     | 15/30 [3:45:47<5:18:57, 1275.86s/it]

[I 2026-03-03 20:30:20,282] Trial 14 finished with value: 0.6260133540909348 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.007170077219935868, 'depth': 10, 'l2_leaf_reg': 3.7266604009009554, 'bagging_temperature': 0.5919889644126739, 'border_count': 146, 'random_strength': 0.3861050275239559, 'one_hot_max_size': 7}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  53%|█████▎    | 16/30 [3:56:58<4:15:13, 1093.83s/it]

[I 2026-03-03 20:41:31,386] Trial 15 finished with value: 0.626097179976659 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.01129726539405628, 'depth': 9, 'l2_leaf_reg': 6.165462896506126, 'bagging_temperature': 0.8831978917718473, 'border_count': 79, 'random_strength': 0.8485876942118266, 'one_hot_max_size': 7}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  57%|█████▋    | 17/30 [4:21:34<4:21:51, 1208.55s/it]

[I 2026-03-03 21:06:06,721] Trial 16 finished with value: 0.6257407803183375 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.0027368472440095926, 'depth': 8, 'l2_leaf_reg': 4.017985108071021, 'bagging_temperature': 0.5814785360369703, 'border_count': 162, 'random_strength': 0.009480239306178695, 'one_hot_max_size': 8}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  60%|██████    | 18/30 [5:02:21<5:16:09, 1580.78s/it]

[I 2026-03-03 21:46:54,005] Trial 17 finished with value: 0.6249810453650396 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.003252094532012051, 'depth': 10, 'l2_leaf_reg': 7.722794361651064, 'bagging_temperature': 0.7931981320459465, 'border_count': 57, 'random_strength': 1.0122198715871569, 'one_hot_max_size': 5}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  63%|██████▎   | 19/30 [5:12:19<3:55:43, 1285.74s/it]

[I 2026-03-03 21:56:52,481] Trial 18 finished with value: 0.6264616841854922 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.013996525374448761, 'depth': 9, 'l2_leaf_reg': 4.89411787581432, 'bagging_temperature': 0.9968020465573904, 'border_count': 103, 'random_strength': 0.2165806142722649, 'one_hot_max_size': 10}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  67%|██████▋   | 20/30 [5:40:09<3:53:29, 1400.94s/it]

[I 2026-03-03 22:24:41,901] Trial 19 finished with value: 0.6248930832216182 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.0040222579755594574, 'depth': 6, 'l2_leaf_reg': 2.7450563612580403, 'bagging_temperature': 0.49689257542301124, 'border_count': 199, 'random_strength': 0.741455522084115, 'one_hot_max_size': 2}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  70%|███████   | 21/30 [5:49:54<2:53:25, 1156.13s/it]

[I 2026-03-03 22:34:27,275] Trial 20 finished with value: 0.6257027790472411 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.012319061741396605, 'depth': 8, 'l2_leaf_reg': 7.849895541669513, 'bagging_temperature': 0.6761099754470647, 'border_count': 133, 'random_strength': 1.2889882782563784, 'one_hot_max_size': 8}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  73%|███████▎  | 22/30 [6:02:03<2:17:02, 1027.77s/it]

[I 2026-03-03 22:46:35,660] Trial 21 finished with value: 0.626425153980009 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.01165586839373077, 'depth': 9, 'l2_leaf_reg': 4.7464093468748505, 'bagging_temperature': 0.9962253844052451, 'border_count': 100, 'random_strength': 0.23559872062329498, 'one_hot_max_size': 10}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 10. Best value: 0.626568:  77%|███████▋  | 23/30 [6:14:09<1:49:21, 937.31s/it]

[I 2026-03-03 22:58:41,988] Trial 22 finished with value: 0.6265659749710515 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.015253859042853774, 'depth': 10, 'l2_leaf_reg': 5.086740692305889, 'bagging_temperature': 0.8417030516052268, 'border_count': 91, 'random_strength': 0.21030045046199133, 'one_hot_max_size': 10}. Best is trial 10 with value: 0.6265680541198797.

Best trial: 23. Best value: 0.626896:  80%|████████  | 24/30 [6:23:13<1:21:56, 819.46s/it]

[I 2026-03-03 23:07:46,563] Trial 23 finished with value: 0.6268955252762829 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.023025479971930125, 'depth': 10, 'l2_leaf_reg': 7.5618316883239896, 'bagging_temperature': 0.8624808991805706, 'border_count': 62, 'random_strength': 0.3614099966624804, 'one_hot_max_size': 8}. Best is trial 23 with value: 0.6268955252762829.

Best trial: 24. Best value: 0.626902:  83%|████████▎ | 25/30 [6:28:16<55:21, 664.38s/it]

[I 2026-03-03 23:12:49,169] Trial 24 finished with value: 0.6269020923088026 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.17491200113602548, 'depth': 10, 'l2_leaf_reg': 7.728745475203319, 'bagging_temperature': 0.8698601875850904, 'border_count': 61, 'random_strength': 0.41567687837684253, 'one_hot_max_size': 9}. Best is trial 24 with value: 0.6269020923088026.

Best trial: 24. Best value: 0.626902:  87%|████████▋ | 26/30 [6:31:59<35:27, 531.99s/it]

[I 2026-03-03 23:16:32,286] Trial 25 finished with value: 0.6260099788982771 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.23722716048238665, 'depth': 9, 'l2_leaf_reg': 7.589863390703105, 'bagging_temperature': 0.9275916119933421, 'border_count': 57, 'random_strength': 0.4381497805285983, 'one_hot_max_size': 8}. Best is trial 24 with value: 0.6269020923088026.

Best trial: 24. Best value: 0.626902:  90%|█████████ | 27/30 [6:36:41<22:50, 456.80s/it]

[I 2026-03-03 23:21:13,678] Trial 26 finished with value: 0.6268378581740423 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.20207061492428063, 'depth': 10, 'l2_leaf_reg': 7.003425927703777, 'bagging_temperature': 0.78773642442103, 'border_count': 63, 'random_strength': 0.386353635100645, 'one_hot_max_size': 9}. Best is trial 24 with value: 0.6269020923088026.

Best trial: 24. Best value: 0.626902:  93%|█████████▎| 28/30 [6:40:42<13:04, 392.30s/it]

[I 2026-03-03 23:25:15,470] Trial 27 finished with value: 0.6264290935596806 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.18189424440159324, 'depth': 9, 'l2_leaf_reg': 6.780723052916662, 'bagging_temperature': 0.7794727485249376, 'border_count': 60, 'random_strength': 0.8391187701157254, 'one_hot_max_size': 9}. Best is trial 24 with value: 0.6269020923088026.

Best trial: 24. Best value: 0.626902:  97%|█████████▋| 29/30 [6:45:46<06:05, 365.84s/it]

[I 2026-03-03 23:30:19,553] Trial 28 finished with value: 0.6256188028250649 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.16695749465927126, 'depth': 10, 'l2_leaf_reg': 2.9799889765878853, 'bagging_temperature': 0.9032047917147669, 'border_count': 44, 'random_strength': 0.40853533406730624, 'one_hot_max_size': 9}. Best is trial 24 with value: 0.6269020923088026.

Best trial: 24. Best value: 0.626902: 100%|██████████| 30/30 [6:49:41<00:00, 819.38s/it]

[I 2026-03-03 23:34:14,006] Trial 29 finished with value: 0.6229540186852001 and parameters: {'loss_function': 'CrossEntropy', 'learning_rate': 0.4251974417106103, 'depth': 8, 'l2_leaf_reg': 3.888306735313911, 'bagging_temperature': 0.5999136507716738, 'border_count': 32, 'random_strength': 0.5881301456190623, 'one_hot_max_size': 6}. Best is trial 24 with value: 0.6269020923088026.

In [13]:
# Вывод лучших параметров
print("Best trial:")
trial = study.best_trial
print(f"AUC: {trial.value}")
print("Params:")
for key, value in trial.params.items():
    print(f"    {key}: {value}")

Best trial:
AUC: 0.6269020923088026
Params:
    loss_function: CrossEntropy
    learning_rate: 0.17491200113602548
    depth: 10
    l2_leaf_reg: 7.728745475203319
    bagging_temperature: 0.8698601875850904
    border_count: 61
    random_strength: 0.41567687837684253
    one_hot_max_size: 9

In [15]:
study.best_params

{'loss_function': 'CrossEntropy',
 'learning_rate': 0.17491200113602548,
 'depth': 10,
 'l2_leaf_reg': 7.728745475203319,
 'bagging_temperature': 0.8698601875850904,
 'border_count': 61,
 'random_strength': 0.41567687837684253,
 'one_hot_max_size': 9}

In [16]:
params = {
    'iterations': 2000,
    'early_stopping_rounds': 200,
    'eval_metric': 'AUC',
    'loss_function': study.best_params["loss_function"],
    'task_type': 'CPU',
    'thread_count': -1,
    'random_seed': 42,
    'verbose': False,
    'learning_rate': study.best_params["learning_rate"],
    'depth': study.best_params["depth"],
    'l2_leaf_reg': study.best_params["l2_leaf_reg"],
    'bagging_temperature': study.best_params["bagging_temperature"],
    'border_count': study.best_params["border_count"],
    'random_strength': study.best_params["random_strength"],
    'one_hot_max_size':  study.best_params["one_hot_max_size"],
}

# Обучаем модель
model = CatBoostClassifier(**params)
model.fit(train_pool, eval_set=val_pool, verbose=50)

0:	test: 0.5816443	best: 0.5816443 (0)	total: 1.31s	remaining: 43m 38s
50:	test: 0.6253167	best: 0.6269021 (34)	total: 1m 2s	remaining: 39m 56s
100:	test: 0.6168027	best: 0.6269021 (34)	total: 2m 9s	remaining: 40m 33s
150:	test: 0.6130649	best: 0.6269021 (34)	total: 3m 18s	remaining: 40m 27s
200:	test: 0.6107269	best: 0.6269021 (34)	total: 4m 25s	remaining: 39m 33s
Stopped by overfitting detector  (200 iterations wait)

bestTest = 0.6269020923
bestIteration = 34

Shrink model to first 35 iterations.

In [17]:
model.save_model("model.cbm")